### PR TITLE
Some preparations for KDE6/QT6

### PR DESCRIPTION
**Pull request by t-8ch**
These are some cleanups I encountered when trying to build for KDE6/QT6.
Most of them are already applicable today.

Feel free to pick up single commits now, or incorporate them into your migration work.

### CODE REVIEW

**Comment by dragotin** [comment]
Thanks a lot, that is very appreciated. 

FYI, my plan is as follows: I am currently working on the (already way to big) branch [newshared](https://github.com/dragotin/kraft/tree/newshared) for Kraft 2.0 as described in the [discussion](https://github.com/dragotin/kraft/discussions/197). Once that is mergeable, it will be merged to master. Than, the port to Qt6 can happen on master easily.

The stable 1.x version will be maintained in a branch after that.

**Comment by t-8ch** [comment]
It didn't work. But it should be fixable in a reasonable manner.

**Comment by t-8ch** [comment]
That seems to have worked. I dropped the breaking commit, and will see what is the issue.

**Comment by dragotin** [comment]
@t-8ch the branch https://github.com/dragotin/kraft/tree/portqt6_1 now builds against qt6 and also works with KF6. That makes this particular PR a bit redundant, but would you mind double checking the cmake files in the branch if you have a minute? Thanks a lot.

**Comment by t-8ch** [comment]
@dragotin Looks good in general.

Testing seems to be broken when building out of tree.
Changing the test definitions to `add_test(NAME t_unitman COMMAND t_unitman)` fixes it as it refers to the actual target.

**Comment by t-8ch** [comment]
Drop `cmake_minimum_required()` from `tests/CMakeLists.txt`.

**Pull request closed without merging**
