### PR TITLE
Fix some warnings, deprecations & optimize code

### PR DESCRIPTION
**Pull request by alex1701c**
Just some small changes after playing around with this project for a bit ;)

### CODE REVIEW

**Comment by dragotin** [comment]
Thank you very much for your work, and my apologies that it took so long to answer, I have been on vacation. 

I am happy to merge, but would you mind removing the commented declarations that are not longer needed? That would clean up even more ;-)

Thanks!

**Comment by alex1701c** [comment]
I commented out unused variables, in case they were used in a commented out debug statement. Should I them remove both?

**Comment by dragotin** [comment]
Yes, please, just remove them.

**Comment by dragotin** [comment]
Thanks :+1:

**Pull request merged**
