### PR TITLE
Fix build with akonadi-contacts 22.04

### PR DESCRIPTION
**Pull request by tcberner**

### CODE REVIEW

**Comment by dragotin** [comment]
Hi @tcberner thanks for your PR! 
I am having trouble to compile that on older versions (here: 21.12) because the include `AkonadiContact/akonadi-contact_version.h` can not be found, but is included unconditionally.

An earlier check uses `AKONADI_VERSION` to check for the version of Akonadi (probably in general, not specifically the contact part) - would that be an option?

What do you recommend?

**Comment by tcberner** [comment]
> Hi @tcberner thanks for your PR! I am having trouble to compile that on older versions (here: 21.12) because the include `AkonadiContact/akonadi-contact_version.h` can not be found, but is included unconditionally.
> 
> An earlier check uses `AKONADI_VERSION` to check for the version of Akonadi (probably in general, not specifically the contact part) - would that be an option?
> 
> What do you recommend?

Oh sorry, you are right -- that file is indeed new too in 22.04. 
I guess the easiest thing would be to check the version in cmake

**Comment by dragotin** [comment]
What do you think about ec3bbf65fad73605ab9d16a4d09e9f1b4f6c47bf?

**Comment by tcberner** [comment]
> What do you think about [ec3bbf6](https://github.com/dragotin/kraft/commit/ec3bbf65fad73605ab9d16a4d09e9f1b4f6c47bf)?

Looks like it should work to me, apart from the one unmasked include.

**Comment by dragotin** [comment]
Indeed, thanks :-)

**Pull request merged**
